version: '3.8'

services:
  # MongoDB Database avec configuration optimisée
  mongodb:
    image: mongo:6.0
    container_name: smartsupply-mongodb-standalone
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smartsupply
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/mongod.conf:/etc/mongod.conf:ro
      - mongodb_backups:/backups
      - mongodb_logs:/var/log/mongodb
    networks:
      - mongodb-network
    command: mongod --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

  # MongoDB Express (Interface web pour MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: smartsupply-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - mongodb-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

  # Backup automatique MongoDB
  mongodb-backup:
    image: mongo:6.0
    container_name: smartsupply-mongodb-backup
    restart: "no"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/smartsupply?authSource=admin
    volumes:
      - mongodb_backups:/backups
      - ./scripts/backup-mongodb.sh:/backup-mongodb.sh:ro
    networks:
      - mongodb-network
    depends_on:
      - mongodb
    command: /backup-mongodb.sh
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  mongodb_backups:
    driver: local
  mongodb_logs:
    driver: local

networks:
  mongodb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
