version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: smartsupply-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smartsupply
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/data/logs
      - mongodb_backups:/data/backups
    networks:
      - smartsupply-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: smartsupply-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/smartsupply?authSource=admin
      JWT_SECRET: your-jwt-secret-here
      STRIPE_SECRET_KEY: your-stripe-secret-key
      SENDGRID_API_KEY: your-sendgrid-api-key
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - smartsupply-network

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: smartsupply-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - frontend_logs:/var/log/nginx
    networks:
      - smartsupply-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: smartsupply-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - smartsupply-network

volumes:
  mongodb_data:
  mongodb_logs:
  mongodb_backups:
  backend_logs:
  frontend_logs:

networks:
  smartsupply-network:
    driver: bridge
