version: '3.8'

services:
  # Frontend React SmartSupply Health
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartsupply-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - smartsupply-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: smartsupply-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - smartsupply-network
    depends_on:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

volumes:
  nginx_logs:
    driver: local

networks:
  smartsupply-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
