version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: smartsupply-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smartsupply
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - smartsupply-network

  # SmartSupply Health Application
  app:
    build: .
    container_name: smartsupply-app
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password123@mongodb:27017/smartsupply?authSource=admin
      JWT_SECRET: your-jwt-secret-here
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - smartsupply-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: smartsupply-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - smartsupply-network

volumes:
  mongodb_data:


networks:
  smartsupply-network:
    driver: bridge
