name: Deploy SmartSupply Health

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Create environment file
      run: |
        echo "NODE_ENV=production" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
        echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env
        
    - name: Build Docker images
      run: |
        docker-compose build
        
    - name: Run tests (if available)
      run: |
        # Add your test commands here
        echo "Running tests..."
        # docker-compose run --rm backend npm test
        # docker-compose run --rm frontend npm test
        
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # This could be pushing to a registry, deploying to a server, etc.
        
    - name: Health check
      run: |
        echo "Running health checks..."
        # Add health check commands here





