name: 🧪 PREPROD Pipeline - Deploy to Pre-Production

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test, main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preprod'
        type: choice
        options:
        - preprod

env:
  # Pre-Production Environment Configuration
  ENVIRONMENT: preprod
  AZURE_CONTAINER_REGISTRY: smartsupplyregistry.azurecr.io
  CONTAINER_APP_NAME: smartsupply-health-preprod
  RESOURCE_GROUP: SmartSupply-Health-RG
  LOCATION: East US
  # Pre-Production Resource Limits (Lower for cost optimization)
  CPU_LIMIT: 1.0
  MEMORY_LIMIT: 2Gi
  MIN_REPLICAS: 1
  MAX_REPLICAS: 5

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_APP_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=test-latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Pre-Production Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: smartsupplyacr
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

    - name: Run Health Check
      run: |
        echo "Waiting for pre-production deployment to be ready..."
        sleep 60
        # Get the preprod app URL
        APP_URL=$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
        echo "Testing health endpoint: https://$APP_URL/health"
        curl -f https://$APP_URL/health || exit 1
        echo "✅ Pre-production deployment successful!"

    - name: Verify Pre-Production Deployment
      run: |
        echo "🧪 Pre-production deployment completed!"
        echo "Environment: ${{ env.ENVIRONMENT }}"
        echo "Container App: ${{ env.CONTAINER_APP_NAME }}"
        echo "Resources: ${{ env.CPU_LIMIT }} CPU, ${{ env.MEMORY_LIMIT }} Memory"
        echo "Scaling: ${{ env.MIN_REPLICAS }}-${{ env.MAX_REPLICAS }} replicas"
        
        # Get the preprod URL
        APP_URL=$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
        echo "🌐 Pre-production URL: https://$APP_URL"
        echo "🔍 Health Check: https://$APP_URL/health"

    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const APP_URL = `${{ env.AZURE_CONTAINER_REGISTRY }}`.replace('.azurecr.io', '') + '.azurecontainerapps.io';
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🧪 **Pre-Production deployment successful!**
            
            **Environment:** ${{ env.ENVIRONMENT }}
            **Container App:** ${{ env.CONTAINER_APP_NAME }}
            **Resources:** ${{ env.CPU_LIMIT }} CPU, ${{ env.MEMORY_LIMIT }} Memory
            **Scaling:** ${{ env.MIN_REPLICAS }}-${{ env.MAX_REPLICAS }} replicas
            
            **Pre-Production URL:** https://${{ env.CONTAINER_APP_NAME }}.${APP_URL}
            **Health Check:** https://${{ env.CONTAINER_APP_NAME }}.${APP_URL}/health
            
            You can test your changes in this pre-production environment before merging to main.`
          });
